# The URL the site will be built for
base_url = "https://pedropontesgarcia.com"
default_language = "en"
taxonomies = [{name = "tags", feed = true}]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "tabi"
title = "Pedro Pontes García"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
external_links_class = "external"

[search]
index_format = "elasticlunr_json" # Or the less efficient "elasticlunr_javascript".
include_title = true
include_description = true
include_path = true
include_content = true

[languages.es]
title = "Pedro Pontes García"
taxonomies = [{name = "tags", feed = true}]

[extra]
# Put all your custom variables here
menu = [
    { name = "posts", url = "posts", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "photo", url = "photo", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "cv", url = "docs/cv.pdf", trailing_slash = false },
]
copyright = "© $CURRENT_YEAR Pedro Pontes García $SEPARATOR [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
date_formats = [
    { lang = "es", long = "%-d de %B de %Y", short = "%-d %b %Y", archive = "%-d de %B" },
    { lang = "en", long = "%B %-d, %Y", short = "%b %-d, %Y", archive = "%b %-d" },
]
separator = "&nbsp;&nbsp;|&nbsp;&nbsp;"
tag_sorting = "frequency"
skin = "forest"
