# The URL the site will be built for
base_url = "https://pedropontesgarcia.com"
default_language = "en"
taxonomies = [{name = "tags", feed = true}]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "tabi"
title = "Pedro Pontes García"

[markdown]
external_links_class = "external"
external_links_target_blank = true

[markdown.highlighting]
theme = "catppuccin-frappe"
style = "class"

[search]
index_format = "elasticlunr_json" # Or the less efficient "elasticlunr_javascript".
include_title = true
include_description = true
include_path = true
include_content = true

# [languages.es]
# title = "Pedro Pontes García"
# taxonomies = [{name = "tags", feed = true}]

[extra]
# Put all your custom variables here
menu = [
    { name = "home", url = "", trailing_slash = false },
    { name = "projects", url = "projects", trailing_slash = true },
    # { name = "photo", url = "photo", trailing_slash = true },
    # { name = "tags", url = "tags", trailing_slash = true },
    # { name = "archive", url = "archive", trailing_slash = true },
    # { name = "misc", url = "misc", trailing_slash = true },
    { name = "cv", url = "cv", trailing_slash = false },
]
copyright = "© $CURRENT_YEAR Pedro Pontes García $SEPARATOR [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
date_formats = [
    { lang = "es", long = "d 'de' MMMM 'de' yyyy", short = "d MMM yyyy", archive = "d 'de' MMMM" },
    { lang = "en", long = "MMMM d, yyyy", short = "MMM d, yyyy", archive = "MMM d" },
]
separator = "&nbsp;&nbsp;|&nbsp;&nbsp;"
tag_sorting = "frequency"
skin = "forest"
stylesheets = ["cv.css"]
